export const GET_DOCUMENTS_SUCCESS = 'GET_DOCUMENTS_SUCCESS';
export const EDIT_DOCUMENT = 'EDIT_DOCUMENT';
export const EDIT_DOCUMENT_CANCEL = 'EDIT_DOCUMENT_CANCEL';
export const SAVE_DOCUMENT = 'SAVE_DOCUMENT';
export const ADD_DOCUMENT = 'ADD_DOCUMENT';
// export const GET_DOCUMENTS_FAIL = 'GET_DOCUMENTS_FAIL';