export const GET_PARTICIPANTS = 'GET_PARTICIPANTS';
export const DELETE_PARTICIPANT = 'DELETE_PARTICIPANT';
export const ADD_PARTICIPANT = 'ADD_PARTICIPANT';
export const EDIT_PARTICIPANT = 'EDIT_PARTICIPANT';
export const EDIT_PARTICIPANT_CANCEL = 'EDIT_PARTICIPANT_CANCEL';
export const SAVE_PARTICIPANT = 'SAVE_PARTICIPANT';