export const GET_PARTICIPANTS = 'GET_PARTICIPANTS';
export const DELETE_PARTICIPANT = 'DELETE_PARTICIPANT';
export const EDIT_PARTICIPANT = 'EDIT_PARTICIPANT';
export const SAVE_PARTICIPANT = 'SAVE_PARTICIPANT';